.PHONY: clean All

All:
	@echo "----------Building project:[ labb4 - Debug ]----------"
	@cd "labb4" && $(MAKE) -f  "labb4.mk"
clean:
	@echo "----------Cleaning project:[ labb4 - Debug ]----------"
	@cd "labb4" && $(MAKE) -f  "labb4.mk" clean
