.PHONY: clean All

All:
	@echo "----------Building project:[ MOP_bouncing_water - Debug ]----------"
	@cd "MOP_bouncing_water" && "$(MAKE)" -f  "MOP_bouncing_water.mk"
clean:
	@echo "----------Cleaning project:[ MOP_bouncing_water - Debug ]----------"
	@cd "MOP_bouncing_water" && "$(MAKE)" -f  "MOP_bouncing_water.mk" clean
